# Generated by Django 5.2.2 on 2025-06-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeleteLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_username', models.CharField(max_length=150)),
                ('deleted_role', models.CharField(max_length=20)),
                ('reason', models.TextField()),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_by', models.CharField(max_length=150)),
            ],
        ),
    ]
