# Generated by Django 5.2.3 on 2025-06-16 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_product_alter_customuser_role_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyChainStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Material', 'Material'), ('Manufacturing', 'Manufacturing'), ('Packaging', 'Packaging'), ('Dispatch', 'Dispatch'), ('Completed', 'Completed')], max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SupplyChainItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.orderitem')),
                ('current_stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth_app.supplychainstage')),
            ],
        ),
        migrations.CreateModel(
            name='SupplyChainHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='auth_app.supplychainitem')),
                ('from_stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='from_history', to='auth_app.supplychainstage')),
                ('to_stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='to_history', to='auth_app.supplychainstage')),
            ],
        ),
    ]
