# Generated by Django 5.2.3 on 2025-06-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_supplychainstage_supplychainitem_supplychainhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplychainitem',
            name='current_stage',
        ),
        migrations.RemoveField(
            model_name='supplychainitem',
            name='order_item',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('Material', 'Material'), ('Manufacturing', 'Manufacturing'), ('Packaging', 'Packaging'), ('Dispatch', 'Dispatch'), ('Completed', 'Completed')], default='Material', max_length=20),
        ),
        migrations.DeleteModel(
            name='SupplyChainHistory',
        ),
        migrations.DeleteModel(
            name='SupplyChainStage',
        ),
        migrations.DeleteModel(
            name='SupplyChainItem',
        ),
    ]
